steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin:latest'
      - '.'
    dir: 'admin'
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'palladium-admin'
      - '--zone=us-central1-a'
      - '--tunnel-through-iap'
      - '--command=sudo gcloud auth configure-docker us-central1-docker.pkg.dev --quiet && sudo docker pull us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin:$BUILD_ID && sudo docker pull us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin:latest && sudo systemctl daemon-reload && sudo systemctl restart palladium-admin'


images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/palladium/admin:latest'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/palladium-admin@$PROJECT_ID.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY


